name: "Release and Publish"

on:
  push:
    tags:
      - 'v*' # ex: "v1.0"

jobs:
  build:
    name: "Build Test"
    uses: ./.github/workflows/build.yml

  build_source:
    name: "Build Source"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install Dependencies
        run: python -m pip install -U "jupyterlab>=4.0.0,<5" "yw-core>=0.1.0,<1"

      - name: Package the extension
        run: |
          set -eux
          
          python -m pip install --upgrade pip
          pip install build
          python -m build
          
      - name: Upload extension packages
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts
          path: ./dist/yw_jupyter*

  publish_to_pypi:
    name: "Publish to PyPI"
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build_source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ./dist
