name: "Release and Publish"

on:
  push:
    tags:
      - 'v*' # ex: "v1.0"

jobs:
  build:
    name: "Build Test"
    uses: ./.github/workflows/build.yml

  publish_to_pypi:
    name: "Publish to PyPI"
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
          path: ./dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ./dist
